[package]
name = "bluey"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"]}
ffmpeg-next = "7.1.0"
anyhow = "1.0.97"
image = "0.25.5"
log = "0.4.26"
indicatif = "0.17.11"